[package]
name = "pet-the-cats"
version = "0.1.0"
authors = ["Tom Olivier <contact.tom60@proton.me>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
ratatui = "0.24.0"
rust-i18n = "2.2.1"
serde = { version = "1.0", features = ["derive"] }
sys-locale = "0.3.1"
toml = "0.8.8"
